{{- if not (.Capabilities.APIVersions.Has "v1/Secret") -}}
{{- fail "Secrets API not available" -}}
{{- end -}}
{{- if and .Values.smokeTest.enabled (not (.Lookup "v1" "Secret" (include "orchestra.namespace" .) (include "orchestra.fullname" .))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: orchestra-postgres
  labels:
    {{- include "orchestra.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Placeholder; the operator is expected to overwrite this with the
  # real PG password before installing.
  password: changeme
{{- end }}
